apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxhello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxhello
  template:
    metadata:
      labels:
        app: nginxhello
    spec:
      containers:
        - name: nginxhello
          image: alexbit2018/nginx:1.0.0 # {"$imagepolicy": "flux-system:nginxhello"}
          ports:
            - containerPort: 80
