apiVersion: apps/v1
kind: Deployment
metadata:
  name: zot
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zot
  template:
    metadata:
      labels:
        app: zot
    spec:
      containers:
        - name: zot
          image: ghcr.io/project-zot/zot:v2.1.18
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: zot-data
              mountPath: /var/lib/registry
      volumes:
        - name: zot-data
          persistentVolumeClaim:
            claimName: zot-data