apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nginxhello-kustomization.yaml
- zot-kustomization.yaml
- imagerepos-kustomization.yaml
- imagepolicies-kustomization.yaml
- imageautos-kustomization.yaml
